"""
The file is generated by django-echarts {{ version }}.
Now you can add site urls to the entry urlpatterns in project urls.py.
Example:
    urlpatterns = [
        # Other urlpatterns
        path('', site_obj.urls),
    ]

"""
from django_echarts.entities import Copyright
from django_echarts.starter.sites import DJESite
{% if use_chart %}
from pyecharts import options as opts
from pyecharts.charts import Bar
{% endif %}

__all__ = ['site_obj']

site_obj = DJESite(
    site_title='{{ site_title }}'
)

site_obj.add_widgets(
    copyright_=Copyright(start_year={{ start_year }}, powered_by='{{ powered_by }}')
)


@site_obj.register_chart
def my_first_chart():
    {% if use_chart %}
    bar = Bar().add_xaxis(
        ["Nanping", "Sanming", "Longyan", "Ningde", "Zhangzhou", "Fuzhou", "Quanzhou", "Putian", "Xiamen"]).add_yaxis(
        'Area', [26300, 22900, 19050, 13450, 12600, 12150, 11020, 4119, 1576]
    ).set_global_opts(
        title_opts=opts.TitleOpts(title="The Area of cities In Fujian Province", subtitle="Unit: km3"))
    return bar
    {% else %}
    # Write your pyecharts here.
    # This method must return an object of pycharts.charts.Chart
    pass
    {% endif %}
