# Generated by Django 3.2.11 on 2022-01-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20180208_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='online',
            field=models.BooleanField(default=None, null=True, verbose_name='在线状态'),
        ),
    ]
